before_script:
  - mysql -e 'create database activeuuid_test;'
  - psql -c 'create database activeuuid_test;' -U postgres

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - rbx-2.2.2
  - jruby-9.1.1.0

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-4-1
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-5-0
  - gemfiles/Gemfile.rails-head

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
  exclude:
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-0
    - rvm: jruby-9.1.7.0
      gemfile: gemfiles/Gemfile.rails-5-0
